# available when running the deployment in Pipeline CI
 banzaicloud:
   tags: []
   organization:
     name:
   cluster:
     id:
     name:
     cloud:
     distribution:
     location:
   spark:
     image:
       repositoryPrefix: banzaicloud
       tag:
     executor:
       num:
   bucket:
     storageAccountName:
   secret:
     historyServer:
       name:
   interpreter: Scala
   security:
     enabled: false
